#!/bin/bash

cd /home/pi/python

python tdtool-with-sensors.py -d 2367754
python tdtool-with-sensors.py -d 2777935
python tdtool-with-sensors.py -d 2821615  
python tdtool-with-sensors.py -d 3017840  

while true 
do
  python tdtool-with-sensors.py -d 2367754  >> TempLog.dat
  python tdtool-with-sensors.py -d 2777935  >> TempLog.dat

  python tdtool-with-sensors.py -d 2821615  >> TempLogBad.dat
  python tdtool-with-sensors.py -d 3017840  >> TempLogBad.dat

  sleep 600
done

